[package]
name        = "gremp"
license     = "MIT"
description = "A minimal, nifty grep implementation."
version     = "0.1.0"
authors     = ["Crispin Koech <crispinkoech.ck@gmail.com>"]
edition     = "2018"

[dependencies]
